export const postData = [
	{
		name: 'Post name 1',
		url: 'https://www.ivertech.com/Articles/Images/KoalaBear200x200.jpg',
		like: '11',
		userName: 'Somebody',
		comment: 'new comment',
		id: 1,
	},
	{
		name: 'Post name 2',
		url: 'https://www.ivertech.com/Articles/Images/KoalaBear200x200.jpg',
		like: '11',
		userName: 'Somebody',
		comment: 'new comment',
		id: 2,
	},
	{
		name: 'Post name 3',
		url: 'https://www.ivertech.com/Articles/Images/KoalaBear200x200.jpg',
		like: '11',
		userName: 'Somebody',
		comment: 'new comment',
		id: 3,
	},
	{
		name: 'Post name 4',
		url: 'https://www.ivertech.com/Articles/Images/KoalaBear200x200.jpg',
		like: '11',
		userName: 'Somebody',
		comment: 'new comment',
		id: 4,
	},
	{
		name: 'Post name 5',
		url: 'https://www.ivertech.com/Articles/Images/KoalaBear200x200.jpg',
		like: '11',
		userName: 'Somebody',
		comment: 'new comment',
		id: 5,
	},
];
